//! Text Generation Pipeline Configuration and Execution.
//!
//! This module defines the structures and execution logic required to
//! configure, initialize, and run a text generation workflow. It supports
//! standard generation as well as Knowledge-Augmented Generation (KAG/RAG) by
//! integrating a retrieval phase before invocation of the completion model.

use std::{
  fmt::Debug,
  time::{Duration, Instant},
};

use anyhow::Context;
use log::{debug, info, trace, warn};
use minijinja::Environment;
use serde::Serialize;

use crate::{cli::generation::Generation, config::Config, retrieval};

/// Represents the final payload returned by the generation phase
#[derive(Debug, Serialize)]
pub struct Output {
  /// The consolidated text response generated by the language model
  pub result: String,
  /// Comprehensive execution metrics and metadata for the generation pipeline
  pub stats: Stats,
}

/// Operational metrics captured during the generation process
#[derive(Debug, Serialize)]
pub struct Stats {
  /// The original system or user prompt processed by the generator
  pub prompt: String,
  /// Detailed metrics from the upstream retrieval phase, if a retriever was
  /// used
  pub retrieval: Option<retrieval::Output>,
  /// The exact configuration parameters used to drive this generation
  /// execution
  pub config: Generation,
  /// The total duration spent during the generation phase
  pub time: Duration,
}

impl Generation {
  /// Executes the complete text generation workflow.
  ///
  /// # Parameters
  ///
  /// - `config`: A reference to the global application configuration
  ///   containing component registries.
  /// - `system_prompt`: An optional baseline system prompt instructing the
  ///   model on its persona or constraints.
  /// - `prompt`: The raw user query or instruction.
  ///
  /// # Errors
  ///
  /// Returns an error wrapped in `anyhow::Result` if:
  /// - A requested provider, retriever, or database component is missing from
  ///   the configuration.
  /// - The backend model fails to initialize.
  /// - The retrieval phase fails during database interaction.
  /// - The completion model fails to stream or return a complete response.
  ///
  /// # Examples
  ///
  /// ```ignore
  /// let generation_args = Generation { ... };
  /// let response = generation_args.generate(
  ///   &config,
  ///   Some("Be concise"),
  ///   "What is NixOS?"
  /// ).await?;
  /// println!("{}", response);
  /// ```
  pub async fn generate(
    &self,
    config: &Config,
    system_prompt: Option<impl AsRef<str>>,
    prompt: impl AsRef<str> + Debug,
    mut environment: Environment<'_>,
  ) -> anyhow::Result<Output> {
    let start = Instant::now();
    info!("Starting text generation workflow...");

    if self.temperature > 1.5 {
      warn!(
        "\
          High temperature ({}) detected. \
          Model output may be highly erratic or nonsensical.\
        ",
        self.temperature
      );
    }

    let rd =
      match &self.augmented_generation {
        Some(ag) => {
          debug!("Resolving retriever component: {}", ag.retriever);
          debug!("Resolving database component: {}", ag.database);

          Some((
          (config.retrievers.get(&ag.retriever).ok_or(anyhow::anyhow!(
            "The requested retriever '{}' is missing from the configuration.",
            ag.retriever
          ))?, &ag.retriever),
          (config.databases.get(&ag.database).ok_or(anyhow::anyhow!(
            "The requested database '{}' is missing from the configuration.",
            ag.database,
          ))?, &ag.database),
        ))
        }
        None => None,
      };

    let provider =
      config.providers.get(&self.provider).ok_or(anyhow::anyhow!(
        "The requested provider '{}' is missing from the configuration.",
        self.provider
      ))?;

    debug!(
      "Initializing {} completion model '{}'",
      self.provider, self.model
    );

    let model = provider
      .completion(&self.model, self.temperature, self.tokens)
      .with_context(|| {
        format!(
          "Failed to initialize the model {} for provider '{}'",
          self.model, self.provider
        )
      })?;

    trace!("Raw User Prompt: {:?}", prompt);

    let retrieval: Option<retrieval::Output> = match rd {
      None => {
        info!("No retriever configured. Proceeding without KAG.");
        None
      }
      Some(((r, r_name), (d, d_name))) => {
        info!(
          "\
            Using retriever '{r_name}' with knowledge store '{d_name}'. \
            Proceeding with KAG.\
          "
        );

        let ret = r.retrieve(prompt.as_ref(), &config.providers, d, d_name,).await.with_context(|| format!(
          "Failed during the knowledge retrieval phase (KAG) on database '{}'",
          d_name
        ))?;

        if !ret.result.is_empty() {
          environment.add_global("RETRIEVAL", &ret.result);
        };

        Some(ret)
      }
    };

    environment.set_undefined_behavior(minijinja::UndefinedBehavior::Strict);

    let prompt = if let Some(system_prompt) = system_prompt {
      environment.add_global("INPUT", prompt.as_ref());
      environment.render_str(system_prompt.as_ref(), minijinja::context! {})
    } else {
      environment.render_str(prompt.as_ref(), minijinja::context! {})
    }
    .context(
      "\
        Failed to render the prompt template: ensure all variables used in \
        the template are provided\
      ",
    )?;

    trace!("Final Prompt being sent to model: {:?}", prompt);
    info!("Sending prompt to the completion model...");

    let generation_start = Instant::now();

    let response = model
      .prompt(&prompt)
      .await
      .context("Failed to generate a response from the model")?;

    info!("Generation completed in {:.2?}", generation_start.elapsed());

    Ok(Output {
      result: response,
      stats: Stats {
        prompt,
        retrieval,
        config: self.clone(),
        time: start.elapsed(),
      },
    })
  }
}
