[providers.ollama]
type = "Ollama"
url = "https://ollama.example.com"

[providers.openai]
type = "OpenAI"
url = "https://openai.example.com/api/v1"
key = "{{ env('OPEN_AI_KEY') or file('.openai') }}"

[databases.neo4j]
type = "Neo4j"
password = "{{ env('NEO4J_PASSWORD') or 'neo4j' }}"

[retrievers.neo4j-embedding-triplet-formal]
type = "Embedder"
provider = "ollama"
model = "embeddinggemma:latest"
top_k = 7
extra.neo4j = {
  type = "Neo4j",
  index = "NODE_INDEX"
}

[retrievers.neo4j-embedding-triplet-text]
type = "Embedder"
provider = "ollama"
model = "embeddinggemma:latest"
top_k = 3

[retrievers.embeddingemma-triplet-text.extra.neo4j]
type = "Neo4j"
neighborhood = 3
index = "MOVIE_INDEX"
translation = {
  type = "TextualTriplet",
  node_formats = {
    "Movie" = "the movie {title}",
    "Person" = "the person {name}"
  },
  property_formats = {
    "Movie" = [
      "{FROM} was released in the year {released}.",
      "The tagline for {FROM} is '{tagline}'."
    ],
    "Person" = [
      "{FROM} was born in the year {born}."
    ]
  },
  relation_formats = {
    "ACTED_IN" = "{FROM} acted in {TO} playing the role(s) of {roles}.",
    "DIRECTED" = "{FROM} directed {TO}.",
    "FOLLOWS" = "{FROM} follows {TO}.",
    "PRODUCED" = "{FROM} produced {TO}.",
    "REVIEWED" = "{FROM} reviewed {TO} with a rating of {rating} and summarized it as '{summary}'.",
    "WROTE" = "{FROM} wrote {TO}."
  }
}
