//! wip

use std::time::{Duration, Instant};

use anyhow::Context;
use hashbrown::HashMap;
use log::{debug, info, trace};
use rig_core::embeddings::Embedding;
use serde::Serialize;

use crate::config::{ComponentName, Database, Provider, Retriever};

mod database;

/// Represents the final consolidated result of a retrieval operation
#[derive(Debug, Serialize)]
pub struct Output {
  /// The formatted text context generated by the underlying retrieval driver
  pub result: String,
  /// Statistical metadata regarding the state or scale of the targeted
  /// retriever
  pub stats: Stats,
}

/// Represents statistical metrics for various retriever engines
#[derive(Debug, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Stats {
  /// Statistics captured during a standard embedding-based retrieval pipeline
  Embedder {
    /// The generated semantic embedding vector
    embedding: Embedding,
    /// Metrics returned by the underlying database backend during the top-k
    /// retrieval phase
    database: database::Stats,
    /// The execution duration spent
    time: Duration,
  },
}

impl Retriever {
  /// Executes the full data retrieval pipeline for a given user query prompt.
  ///
  /// # Parameters
  ///
  /// * `prompt` - The raw string input or user query to generate embeddings
  ///   for and query against.
  /// * `providers` - A reference map of all initialized and available AI
  ///   [`Provider`] components, keyed by their unique [`ComponentName`].
  /// * `database` - A reference to the target [`Database`] backend wrapper
  ///   instance.
  /// * `db_name` - The active [`ComponentName`] identifier of the database,
  ///   used as a key to look up specific backend parameters in the `extra`
  ///   configurations map.
  ///
  /// # Returns
  ///
  /// Returns an `anyhow::Result<String>` containing the consolidated,
  /// structured text context fetched from the storage backend (e.g., a
  /// subgraph converted to text).
  ///
  /// # Errors
  ///
  /// Returns an error if:
  /// * The requested `provider` identifier is not found within the
  ///   `providers` map.
  /// * The embedding generation process fails or times out.
  /// * The database fails to connect, execute the query, or translate the raw
  ///   rows into text.
  pub async fn retrieve(
    &self,
    prompt: &str,
    providers: &HashMap<ComponentName, Provider>,
    database: &Database,
    db_name: &ComponentName,
  ) -> anyhow::Result<Output> {
    let start = Instant::now();

    match self {
      Self::Embedder {
        provider,
        model,
        top_k,
        extra,
      } => {
        info!("KAG enabled: Initializing Neo4j retrieval workflow...");

        let retrieval_start = Instant::now();

        debug!("Initializing embedder model '{}' via '{}'", model, provider);
        let embedder = providers
          .get(provider)
          .ok_or(anyhow::anyhow!(
            "\
            The requested provider '{}' is missing from the \
            configuration.\
          ",
            provider
          ))?
          .embedder(model)
          .with_context(|| {
            format!(
              "Failed to initialize the model {} for provider '{}'",
              model, provider
            )
          })?;

        debug!("Generating embeddings for the user prompt...");
        let embedding = embedder
          .embed_texts(prompt)
          .await
          .context("Failed to generate embeddings for the prompt")?;

        let retrieval = database
          .retrieve_with_embedding(extra.get(db_name), *top_k, &embedding)
          .await
          .with_context(|| {
            format!(
              "Failed to execute vector retrieval for database '{}'",
              db_name
            )
          })?;

        debug!(
          "Generated context buffer of {} bytes.",
          retrieval.result.len()
        );
        trace!("Final Retrieval Buffer Content:\n{:?}", retrieval.result);

        info!(
          "Retrieval workflow completed in {:.2?}",
          retrieval_start.elapsed()
        );

        Ok(Output {
          result: retrieval.result,
          stats: Stats::Embedder {
            embedding,
            database: retrieval.stats,
            time: start.elapsed(),
          },
        })
      }
    }
  }
}
