//! Database Abstraction and Retrieval Orchestration
//!
//! This module acts as the central dispatch layer for all database-specific
//! retrieval operations. It cross-references the active [`Database`] instance
//! configuration with the runtime [`RetrieverExtra`] parameters to execute
//! targeted semantic and structural search operations.

use std::time::Duration;

use rig_core::embeddings::Embedding;
use serde::Serialize;

use crate::config::{Database, RetrieverExtra};

mod neo4j;

/// Represents the final consolidated result of a database retrieval operation
#[derive(Debug, Serialize)]
pub struct Output {
  /// The formatted text context generated by the underlying retrieval
  /// database driver
  pub result: String,
  /// Statistical metadata regarding the state or scale of the targeted
  /// retriever
  pub stats: Stats,
}

/// Represents statistical metrics for various database engines
#[derive(Debug, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Stats {
  /// Statistics specific to a Neo4j graph database instance
  Neo4j {
    /// The total number of vertices present in the graph
    vertices: u32,
    /// The total number of relationships connecting the nodes
    relationships: u32,
    /// The total count of key-value properties stored across all vertices and
    /// relationships
    properties: u32,
    /// The exact duration spent executing the query and processing data
    /// within the database backend
    time: Duration,
  },
}

impl Database {
  /// Routes a semantic embedding query to the appropriate database backend.
  ///
  /// This method acts as a dynamic dispatcher. It matches the structural
  /// variant of the current [`Database`] instance against the
  /// database-specific parameters provided in `config` to trigger specialized
  /// retrieval pipelines.
  ///
  /// # Parameters
  ///
  /// * `config` - Optional extra configuration layout (`RetrieverExtra`).
  ///   This must align with the active database variant.
  /// * `top_k` - The maximum number of base/seed items to retrieve during
  ///   vector similarity lookup.
  /// * `embedding` - The generated semantic [`Embedding`] vector representing
  ///   the incoming user query.
  ///
  /// # Returns
  ///
  /// Returns an `anyhow::Result<String>` containing the consolidated and
  /// formatted text context generated by the underlying retrieval database
  /// driver.
  ///
  /// # Errors
  ///
  /// Returns an error if:
  /// * The target database execution encounters connectivity, driver, or
  ///   query issues.
  /// * There is a structural mismatch (e.g., `Database` is configured for
  ///   Neo4j, but `config` is `None` or mismatching).
  pub async fn retrieve_with_embedding(
    &self,
    config: Option<&RetrieverExtra>,
    top_k: u32,
    embedding: &Embedding,
  ) -> anyhow::Result<Output> {
    match (self, config) {
      (
        Self::Neo4j {
          uri,
          user,
          password,
          database,
        },
        Some(RetrieverExtra::Neo4j {
          index,
          neighborhood,
          translation,
        }),
      ) => {
        neo4j::retrieve_with_embedding(
          uri,
          user,
          password,
          database,
          index,
          top_k,
          *neighborhood,
          translation,
          embedding,
        )
        .await
      }
      (Self::Neo4j { database, .. }, None) => Err(anyhow::anyhow!(
        "\
          Missing configuration parameters for Neo4j database '{}'. \
          Ensure that 'extra' contains a valid 'Neo4j' configuration block \
          matching this retriever.\
        ",
        database
      )),
      #[allow(unreachable_patterns)]
      _ => Err(anyhow::anyhow!(
        "Mismatched database and retriever configuration backend variants."
      )),
    }
  }
}
